version: '3.8'
services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicapp-api
    command: yarn start:dev
    ports:
      - ${PORT}:8800
    # restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
